export default {
    help: require("./help.command"),
    ping: require("./ping.command"),
    onboard: require("./onboard.command"),
    langlist: require("./langlist.command"),
    translate: require("./translate.command"),
    chat: require("./chat.command"),
    meme: require("./meme.command"),
    joke: require("./joke.command"),
    get: require("./get.command"),
    meteo: require("./meteo.command"),
    productos: require("./productos.command"),
    guia: require("./guia.command"),
    contacto: require("./contacto.command"),
    precios: require("./precios.command"),
    pago: require("./pago.command"),
    tarjeta: require("./tarjeta.command"),
}